"""empty message

Revision ID: 811548b18efb
Revises: 
Create Date: 2018-12-22 16:43:52.550306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811548b18efb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserData',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=64), nullable=True),
    sa.Column('Description', sa.String(length=256), nullable=True),
    sa.Column('CreateDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserData')
    # ### end Alembic commands ###
